-- 코드를 입력하세요
WITH RECURSIVE TIMETABLE AS (
    SELECT 0 AS HOUR
    UNION
    SELECT HOUR + 1
    FROM TIMETABLE
    WHERE HOUR < 23
)

SELECT T.HOUR, COUNT(O.DATETIME) AS 'COUNT'
FROM ANIMAL_OUTS AS O RIGHT JOIN TIMETABLE AS T
ON T.HOUR = HOUR(O.DATETIME)
GROUP BY T.HOUR
ORDER BY T.HOUR;