-- 코드를 작성해주세요
WITH PARENT_DATA AS (
    SELECT ID, GENOTYPE AS PARENT_GENOTYPE
    FROM ECOLI_DATA
)

SELECT E.ID, E.GENOTYPE, P.PARENT_GENOTYPE
FROM ECOLI_DATA AS E
JOIN PARENT_DATA AS P
ON E.PARENT_ID = P.ID
WHERE (E.GENOTYPE & P.PARENT_GENOTYPE) = P.PARENT_GENOTYPE
ORDER BY E.ID;