-- 코드를 작성해주세요
SELECT YEAR(e.DIFFERENTIATION_DATE) AS YEAR, (m.max_size - e.SIZE_OF_COLONY) AS YEAR_DEV, e.ID
FROM ECOLI_DATA AS e JOIN (
    SELECT MAX(SIZE_OF_COLONY) AS max_size, YEAR(DIFFERENTIATION_DATE) AS yr
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS m
ON YEAR(e.DIFFERENTIATION_DATE) = m.yr
ORDER BY YEAR, YEAR_DEV;