-- 코드를 작성해주세요
SELECT m.year, m.max_size - e.SIZE_OF_COLONY AS YEAR_DEV, e.ID
FROM ECOLI_DATA AS e JOIN (
    SELECT MAX(SIZE_OF_COLONY) AS max_size, YEAR(DIFFERENTIATION_DATE) AS year
    FROM ECOLI_DATA
    GROUP BY year
) AS m
ON YEAR(e.DIFFERENTIATION_DATE) = m.year
ORDER BY m.year, YEAR_DEV;