-- 코드를 작성해주세요
SELECT SUM(g.SCORE) AS SCORE, e.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM HR_DEPARTMENT AS d JOIN HR_EMPLOYEES AS e
ON d.DEPT_ID = e.DEPT_ID
JOIN HR_GRADE AS g
ON e.EMP_NO = g.EMP_NO
GROUP BY g.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;
